name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # test project
      - run: npm install --ignore-scripts
      - run: npm run prepare
      - run: npm test
      # test node example
      - working-directory: example/node
        run: |
          npm install
          npm run build
          npm test
